install:
	pipenv install django
	pipenv install djangorestframework
	pipenv install requests
up:
	pipenv run python manage.py runserver

makemig:
	pipenv run python manage.py makemigrations

migrate:
	pipenv run python manage.py migrate

