install:
	pipenv install django
	pipenv install djangorestframework
	pipenv install requests
up:
	python manage.py runserver

makemig:
	python manage.py makemigrations

migrate:
	python manage.py migrate

